### ISSUE TITLE
Too few articles crawled with Selenium

### ISSUE THREAD

**Issue by pm5** [disinfoRG/ZeroScraper#39]
Currently there are 3 sites crawled with Selenium: 

15	今日頭條
122	壹讀
123	每日頭條

of which 壹讀 and 每日頭條 are currently active.

On production db, the SQL `SELECT site_id, COUNT(*) FROM Article WHERE site_id = 15 OR site_id = 122 OR site_id = 123 GROUP BY site_id` results in

```
site_id	COUNT(*)
15	3
122	63
123	48
```

Seems to few?

**Comment by andrea-w-wang** [comment]
今日頭條's list of articles would not load when using selenium. However, I think we can use their api `https://www.toutiao.com/api/pc/realtime_news/` to collect article urls. Opening a new issue #109 for 今日頭條 and closing this.
