### ISSUE TITLE
recover from data loss

### ISSUE THREAD

**Issue by pm5** [disinfoRG/ZeroScraper#94]
The main reasons that we want to recover article snapshot data are:

* Some snapshots are not parsed yet before the data loss incident.
* Some snapshots are parsed before the incident and were saved in parser db, but the parser was older at the time and did not extract some of the metadata.  In particular, there were no site GA tracking id extracted for many producers.

To assess the impact of the data loss, a `LossArticle` table was created out of the following query:

```sql
SELECT article_id, site_id, snapshot_count, (SELECT COUNT(*) FROM ArticleSnapshot WHERE article_id = Article.article_id) AS actual_count FROM Article HAVING snapshot_count > 0 AND actual_count = 0
```

The results are:

```

site_id | COUNT(*) |  
-- | -- | --
1 | 804
2 | 545
6 | 8274
8 | 10527
13 | 3500
14 | 13632
15 | 3
16 | 878
96 | 270
98 | 2896
99 | 3921
100 | 946
101 | 941
102 | 2188
104 | 847
105 | 1073
106 | 663
107 | 589
108 | 3941
114 | 816
115 | 1491
116 | 921
117 | 2190
118 | 6416
119 | 4718
120 | 14
121 | 189
122 | 10247
123 | 5908
731 | 2
732 | 42307
751 | 11
752 | 634
753 | 1
789 | 538
1668 | 224
1669 | 46
2922 | 1431
4589 | 685
```

**Comment by chihaoyo** [comment]
We lost 135227 articles.

**Comment by pm5** [comment]
Redid the calculation with all snapshot tables we have:

```sql
CREATE TABLE Snapshot (article_id INT NOT NULL, snapshot_at INT NOT NULL, PRIMARY KEY (article_id, snapshot_at)) SELECT article_id, snapshot_at FROM ArticleSnapshot;
INSERT Snapshot (article_id, snapshot_at) SELECT article_id, snapshot_at FROM ArticleSnapshot202002;
INSERT Snapshot (article_id, snapshot_at) SELECT article_id, snapshot_at FROM ArticleSnapshot202003;
CREATE TABLE SnapshotLoss (article_id INT PRIMARY KEY, site_id INT NOT NULL, snapshot_count INT NOT NULL, actual_count INT NOT NULL) SELECT article_id, site_id, snapshot_count, (SELECT COUNT(*) FROM Snapshot WHERE article_id = Article.article_id) AS actual_count FROM Article WHERE first_snapshot_at < 1582851815 HAVING snapshot_count > 0 AND actual_count = 0;
```

It shows there are still 5351 articles discovered before 2020-02-28 09:03:35, the `MIN(first_snapshot_at)` after the data loss incident, that should have at least one snapshot (`snapshot_count > 0`) but actually has none (`actual_count = 0`).  Grouped into sites:

site_id | loss_count
-- | --
1 | 2
98 | 512
99 | 3328
100 | 16
107 | 6
122 | 642
123 | 225
751 | 1
789 | 538
2922 | 81

Among which sites 122（壹讀）and 123（每日頭條）are not active at the moment(!?) Other than that, I checked a few of these articles and found that they are indeed 404.  This probably means we have 4484 articles lost for good.

**Comment by pm5** [comment]
Since all of the above articles has `snapshot_count` less than 7, the update spider should have checked all of them except for sites 122 and 123.  And since the update spider sets `next_snapshot_at` to zero when it found an article has 404, the following query shows in our db those articles on which the update spider didn't hit a 404 but somehow couldn't grab a snapshot:

```sql
SELECT Article.article_id, Article.site_id, url, next_snapshot_at FROM Article JOIN SnapshotLoss ON Article.article_id = SnapshotLoss.article_id WHERE next_snapshot_at > 0 AND Article.site_id NOT IN (122, 123)
```

and there are only 16 of them 🎉 :

  article_id | site_id | url | next_snapshot_at 
------------|---------|---------------------------------------------------------------|------------------
 1242669 | 100 | https://www.chinatimes.com/realtimenews/20200219003118-260402 | 1582188254 
 1244635 | 100 | https://www.chinatimes.com/realtimenews/20200219004733-260402 | 1582205538 
 1244638 | 100 | https://www.chinatimes.com/realtimenews/20200219004986-260402 | 1582205557 
 1266016 | 100 | https://www.chinatimes.com/realtimenews/20200220004918-260402 | 1582290022 
 1282649 | 100 | https://www.chinatimes.com/realtimenews/20200221005318-260407 | 1582381528 
 1294493 | 100 | https://www.chinatimes.com/realtimenews/20200222003894-260402 | 1582464538 
 1294495 | 100 | https://www.chinatimes.com/realtimenews/20200222003905-260402 | 1582464549 
 1299269 | 100 | https://www.chinatimes.com/realtimenews/20200223000869-260410 | 1582509188 
 1299273 | 100 | https://www.chinatimes.com/realtimenews/20200223000878-260410 | 1582509197 
 1299278 | 100 | https://www.chinatimes.com/realtimenews/20200223000884-260410 | 1582509207 
 1299281 | 100 | https://www.chinatimes.com/realtimenews/20200223000809-260410 | 1582509216 
 1299283 | 100 | https://www.chinatimes.com/realtimenews/20200223000816-260410 | 1582509221 
 1306111 | 100 | https://www.chinatimes.com/realtimenews/20200224003287-260407 | 1582612175 
 1311575 | 100 | https://www.chinatimes.com/realtimenews/20200225002516-260402 | 1582692755 
 1358109 | 100 | https://www.chinatimes.com/realtimenews/20200227004529-260402 | 1582926713 
 1359453 | 100 | https://www.chinatimes.com/realtimenews/20200227004973-260402 | 1582928905 

Looks like they are indeed all 404, it is just that our spider doesn't like the responses from chinatimes.  That means all of the 4484 articles are indeed lost for good, unless we find a way to get them again other than from the sites that published them.

**Comment by pm5** [comment]
It is still possible to get those articles back from some places like archive.org or google search cache.  For example,

* We can get https://www.chinatimes.com/realtimenews/20200227004529-260402 from https://webcache.googleusercontent.com/search?q=cache:bMo4DcU9aRIJ:https://www.chinatimes.com/realtimenews/20200227004529-260402%3Fctrack%3Dpc_main_recmd_p08+&cd=1&hl=fr&ct=clnk&gl=tw&chdtv
* There are many archives for PTT like https://www.pttweb.cc/bbs/Gossiping/M.1582847305.A.A5A for https://www.pttweb.cc/bbs/Gossiping/M.1582847305.A.A5A , https://www.pttweb.cc/bbs/HatePolitics/M.1574072804.A.2DE for https://www.ptt.cc/bbs/HatePolitics/M.1574072804.A.2DE.html

For some of the lost articles I could not find a cached version, though.  Also PTTWeb may need a different parser.

I say we conclude the investigation here, compile a brief report of the incident and the affected data, and open new issues separately for recovering lost data for each of Chinatimes, PTT, and other sites in `SnapshotLoss`, if we want to pursuit the data recovery further, because they all require addition work beyond the capabilities of our current system.

**Comment by pm5** [comment]
Close the issue here.  Open #105 for PTT data.
